Repository 9ITHON/7-ToGetHer-BE, pull requests merged in 2025-07, with the labels that each got.

#34 33/refactor/calendar get
  backend/FETCH_HEAD
  backend/src/main/java/com/together/backend/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/together/backend/domain/calendar/service/CalendarService.java
Labels: 🔨 Refactoring

#46 39/feature/noti time
  backend/src/main/java/com/together/backend/domain/notification/controller/NotificationSettingsController.java
  backend/src/main/java/com/together/backend/domain/notification/model/NotificationType.java
  backend/src/main/java/com/together/backend/domain/notification/model/notification/request/NotificationEnabledRequest.java
  backend/src/main/java/com/together/backend/domain/notification/model/notification/request/NotificationTimeRequest.java
  backend/src/main/java/com/together/backend/domain/notification/model/notification/response/NotificationEnabledResponse.java
  backend/src/main/java/com/together/backend/domain/notification/model/notification/response/NotificationTimeResponse.java
  backend/src/main/java/com/together/backend/domain/notification/service/NotificationIntakeService.java
  backend/src/main/java/com/together/backend/domain/notification/service/NotificationSettingsService.java
Labels: ✨Feature

#56 50/feat/mainpage info
  backend/src/main/java/com/together/backend/domain/couple/model/entity/Couple.java
  backend/src/main/java/com/together/backend/domain/couple/service/CoupleService.java
  backend/src/main/java/com/together/backend/domain/pill/repository/UserPillRepository.java
  backend/src/main/java/com/together/backend/domain/user/controller/MainPageController.java
  backend/src/main/java/com/together/backend/domain/user/model/response/mainpageinfo/PartnerInfoResponse.java
  backend/src/main/java/com/together/backend/domain/user/model/response/mainpageinfo/PillInfoResponse.java
  backend/src/main/java/com/together/backend/domain/user/model/response/mainpageinfo/UserInfoResponse.java
  backend/src/main/java/com/together/backend/domain/user/service/MainPageService.java
Labels: ✨Feature

#58 57/feat/main page
  backend/src/main/java/com/together/backend/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/together/backend/domain/notification/repository/NotificationSettingsRepository.java
  backend/src/main/java/com/together/backend/domain/pill/controller/UserPillController.java
  backend/src/main/java/com/together/backend/domain/pill/model/response/TodayPillResponse.java
  backend/src/main/java/com/together/backend/domain/pill/model/response/UserPillRemainResponse.java
  backend/src/main/java/com/together/backend/domain/pill/repository/UserPillRepository.java
  backend/src/main/java/com/together/backend/domain/pill/service/UserPillService.java
  backend/src/main/java/com/together/backend/global/common/BaseResponseStatus.java
Labels: ✨Feature

#73 68 refactor pill
  backend/src/main/java/com/together/backend/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/together/backend/domain/calendar/dto/CalendarDetailResponse.java
  backend/src/main/java/com/together/backend/domain/calendar/dto/CalendarRecordRequest.java
  backend/src/main/java/com/together/backend/domain/calendar/dto/CalendarRecordResponse.java
  backend/src/main/java/com/together/backend/domain/calendar/dto/CalendarSummaryResponse.java
  backend/src/main/java/com/together/backend/domain/calendar/model/entity/BasicRecord.java
  backend/src/main/java/com/together/backend/domain/calendar/model/entity/MoodType.java
  backend/src/main/java/com/together/backend/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/together/backend/domain/pill/controller/UserPillController.java
  backend/src/main/java/com/together/backend/domain/pill/service/UserPillService.java
  backend/src/main/java/com/together/backend/global/common/BaseResponse.java
  backend/src/main/resources/application.yml
Labels: ✨Feature, 🔨 Refactoring
